### PR TITLE
Feature/upstream merge 16 02

### PR DESCRIPTION
**Pull request by LaurensBER**

### CODE REVIEW

**Comment by LaurensBER** [comment]
Hi, I already did a an upstream merge and fix the merge conflicts. This is in response to: https://github.com/nimbis/cmsplugin-newsplus/pull/5

**Comment by amadornimbis** [comment]
Thanks for the pull request. I'll personally review these changes today or tomorrow, but someone from my team may get to it before me.

**Comment by electroniceagle** [comment]
Thanks for your contribution.  I'll do a release to pypi shortly.

**Comment by electroniceagle** [comment]
```
  File "/Users/bschott/Source/cmsplugin-newsplus/cmsplugin_newsplus/migrations/0002_auto_20150501_0537.py", line 18, in Migration
    field=models.DateTimeField(default=cmsplugin_newsplus.models.get_default_pub_date, verbose_name='Publication date'),
AttributeError: 'module' object has no attribute 'get_default_pub_date'
```

Hmm, so I had to remove 
cmsplugin_newsplus/migrations/0002_auto_20150501_0537.py  because it references a method that doesn't exist.  Can you take another crack at a pull request against master?  The migration should be 0003, not 0002.

**Comment by electroniceagle** [comment]
You can test the repo with make reqs, make test.

**Pull request merged**
